<h1 dir=rtl align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
    SharifML Contest - ML
</font>
</h1>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
   
</font>
</p>

<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
معرفی مجموعه داده
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    در فایل اولیه‌ی این سوال دو مجموعه‌داده با نام‌های <code>train_dataset</code> و <code>test_dataset</code> قرار دارد که به ترتیب مجموعه‌داده مربوط به آموزش و آزمون هستند. این دو به‌ترتیب شامل ۲۵۹۴۱ و ۱۷۰۰ سطر هستند.
    <br>
    ستون‌های این فایل به شرح زیر است:
</font>
</p>

<center>
<div dir=rtl align=center style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>

| <b>نام ویژگی</b> | <b>توضیح ویژگی</b> |
| :---: | :---: |
| <code>Class</code> | ستون هدف که کلاس مربوط به آن گونه است.|
| <code>Others</code> | ویژگی‌هایی که می‌توانید از آنها برای آموزش مدل خود استفاده کنید. |

</font>

<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
خواندن مجموعه‌داده
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>

</font>
</p>

In [31]:
import numpy as np
import pandas as pd
import re
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score

In [32]:
# Read/Load the dataset files
# TODO
train_data = pd.read_csv('train_dataset.csv')
test_data = pd.read_csv('test_dataset.csv')
train_data.head()

,Kingdom,Phylum,Subphylum,Class,Order,Suborder,Family,Genus,Species,Population size,...,Top speed,Weight,Height,Length,Attributes,Distribution,Habits,Diet,Mating_Habits,Population
0,Animalia,Chordata,NaN,Aves,Passeriformes,NaN,Thraupidae,Kleinothraupis,Kleinothraupis atropileus,NaN,...,NaN,NaN,NaN,NaN,"Terrestrial,Not a migrant","{'Geography': {'Continents': 'South America', ...","{'Lifestyle': 'Terrestrial,', 'Seasonal behavi...",NaN,{},"{'Population trend': 'Decreasing', 'Population..."
1,Animalia,Chordata,Vertebrata,Mammalia,Rodentia,NaN,Muridae,Lophuromys,Lophuromys chrysopus,NaN,...,NaN,NaN,NaN,NaN,Terrestrial,"{'Geography': {'Continents': ''}, 'Biome': ['F...",{},NaN,{},"{'Population trend': 'Unknown', 'Population st..."
2,Animalia,Chordata,NaN,Aves,Falconiformes,NaN,Falconidae,Falco,Falco concolor,NaN,...,NaN,NaN,NaN,NaN,"Terrestrial,Congregatory,Social,Migrating","{'Geography': {'Continents': 'Africa, Asia', '...","{'Lifestyle': 'Terrestrial, Congregatory,', 'S...",NaN,{},"{'Population trend': 'Decreasing', 'Population..."
3,Animalia,Chordata,NaN,Aves,Columbiformes,NaN,Columbidae,Turacoena,Turacoena manadensis,NaN,...,NaN,NaN,NaN,NaN,"Terrestrial,Not a migrant","{'Geography': {'Continents': ''}, 'Biome': ['A...","{'Lifestyle': 'Terrestrial,', 'Seasonal behavi...",NaN,{},"{'Population trend': 'Decreasing', 'Population..."
4,Animalia,Chordata,NaN,Aves,Passeriformes,NaN,Estrildidae,Lonchura,Lonchura spectabilis,NaN,...,NaN,NaN,NaN,NaN,"Terrestrial,Not a migrant","{'Geography': {'Continents': ''}, 'Biome': ['A...","{'Lifestyle': 'Terrestrial,', 'Seasonal behavi...",NaN,{},"{'Population trend': 'Stable', 'Population sta..."

In [33]:
# Preprocess the dataset
# TODO
train_data.drop(['Distribution', 'Habits', 'Mating_Habits', 'Population', 'Order', 'Suborder', 'Family', 'Genus', 'Species'], axis=1, inplace=True)
test_data.drop(['Distribution', 'Habits', 'Mating_Habits', 'Population'], axis=1, inplace=True)

train_data['Kingdom'] = train_data['Kingdom'].astype('category').cat.codes
train_data['Phylum'] = train_data['Phylum'].astype('category').cat.codes
train_data['Subphylum'] = train_data['Subphylum'].astype('category').cat.codes
train_data['Attributes'] = train_data['Attributes'].astype('category').cat.codes
train_data['Diet'] = train_data['Diet'].astype('category').cat.codes
test_data['Kingdom'] = test_data['Kingdom'].astype('category').cat.codes
test_data['Phylum'] = test_data['Phylum'].astype('category').cat.codes
test_data['Subphylum'] = test_data['Subphylum'].astype('category').cat.codes
test_data['Attributes'] = test_data['Attributes'].astype('category').cat.codes
test_data['Diet'] = test_data['Diet'].astype('category').cat.codes

for column in ['Weight', 'Height', 'Length', 'Life span', 'Top speed']:
    for element in train_data[column]:
        if type(element) == str:
            numbers = list(map(int, re.findall(r'\d+', element)))
            if len(numbers) == 0:
                train_data[column].replace(element, np.nan, inplace=True)
                print(column)
            train_data[column].replace(element, sum(numbers)/len(numbers), inplace=True)
            
    
    for element in test_data[column]:
        if type(element) == str:
            numbers = list(map(int, re.findall(r'\d+', element)))
            test_data[column].replace(element, sum(numbers)/len(numbers), inplace=True)
            
    train_data[column] = train_data[column].astype(float)
    test_data[column] = test_data[column].astype(float)
            
_class = train_data['Class']
train_data.drop('Class', axis=1, inplace=True)

def find_median(list_):
    _list = []
    for elem in list_:
        if elem == elem:
            _list.append(elem)
    return sorted(_list)[len(_list)//2]

def find_mean(list_):
    _list = []
    for elem in list_:
        if elem == elem:
            _list.append(elem)
    return sum(_list) / len(_list)

for column in train_data.columns:
    if train_data[column].isna().sum() == len(train_data[column]) or test_data[column].isna().sum() == len(test_data[column]):
        train_data.drop(column, axis=1, inplace=True)
        test_data.drop(column, axis=1, inplace=True)
        
def parse_population(value):
    if pd.isna(value) or value.strip().lower() == 'unknown':
        return np.nan
    
    value = value.lower()
    
    if 'below' in value or 'under' in value or '<' in value:
        numbers = re.findall(r'\d+\.?\d*', value.replace(',', ''))
        if numbers:
            return float(numbers[0])
        else:
            return np.nan
    elif 'over' in value or 'above' in value or '>' in value:
        numbers = re.findall(r'\d+\.?\d*', value.replace(',', ''))
        if numbers:
            return float(numbers[0])
        else:
            return np.nan
    
    if '-' in value:
        parts = value.split('-')
        if len(parts) == 2:
            num1 = parse_single_value(parts[0])
            num2 = parse_single_value(parts[1])
            if not np.isnan(num1) and not np.isnan(num2):
                return (num1 + num2) / 2 
            else:
                return np.nan
    
    return parse_single_value(value)

def parse_single_value(value):
    value = value.replace(',', '').replace(' ', '')
    if 'thou' in value or 'k' in value:
        multiplier = 1e3
        value = value.replace('thou', '').replace('k', '')
    elif 'mln' in value or 'm' in value:
        multiplier = 1e6
        value = value.replace('mln', '').replace('m', '')
    elif 'b' in value:
        multiplier = 1e9
        value = value.replace('b', '')
    else:
        multiplier = 1
    
    numbers = re.findall(r'\d+\.?\d*', value)
    if numbers:
        return float(numbers[0]) * multiplier
    else:
        return np.nan
    
train_data['Population size'] = train_data['Population size'].apply(parse_population)
test_data['Population size'] = test_data['Population size'].apply(parse_population)

for column in train_data.columns:
    if column == 'Population size':
        _mean = find_mean(train_data[column])
        for i in range(len(train_data[column])):
            if train_data[column][i] != train_data[column][i]:
                train_data[column][i] = _mean
        _mean = find_mean(test_data[column])
        for i in range(len(test_data[column])):
            if test_data[column][i] != test_data[column][i]:
                test_data[column][i] = _mean
    else:
        if train_data[column].isna().sum() > 0:
            median = find_median(train_data[column])
            for i in range(len(train_data[column])):
                if train_data[column][i] != train_data[column][i]:
                    train_data[column][i] = median
        
        if test_data[column].isna().sum() > 0:
            median = find_median(test_data[column])
            for i in range(len(test_data[column])):
                if test_data[column][i] != test_data[column][i]:
                    test_data[column][i] = median

train_data['Population size'] = (train_data['Population size'] - train_data['Population size'].mean()) / train_data['Population size'].std()


train_data.head(100)

/tmp/ipykernel_32572/2047506195.py:24: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train_data[column].replace(element, sum(numbers)/len(numbers), inplace=True)
/tmp/ipykernel_32572/2047506195.py:24: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  train_data[column].replace(element, sum(numbers)/len(numbers), inplace=True)
/tmp/ipykernel_32572/2047506195.py:30: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test_data[column].replace(element, sum(numbers)/len(numbers), inplace=True)
/tmp/ipykernel_32572/2047506195.py:30: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  test_data[column].replace(element, sum(numbers)/len(numbers), inplace=True)
/tmp/ipykernel_32572/2047506195.py:24: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train_data[column].replace(element, sum(numbers)/len(numbers), inplace=True)
/tmp/ipykernel_32572/2047506195.py:24: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  train_data[column].replace(element, sum(numbers)/len(numbers), inplace=True)
/tmp/ipykernel_32572/2047506195.py:30: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test_data[column].replace(element, sum(numbers)/len(numbers), inplace=True)
/tmp/ipykernel_32572/2047506195.py:30: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  test_data[column].replace(element, sum(numbers)/len(numbers), inplace=True)
/tmp/ipykernel_32572/2047506195.py:24: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train_data[column].replace(element, sum(numbers)/len(numbers), inplace=True)
/tmp/ipykernel_32572/2047506195.py:24: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  train_data[column].replace(element, sum(numbers)/len(numbers), inplace=True)
/tmp/ipykernel_32572/2047506195.py:30: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test_data[column].replace(element, sum(numbers)/len(numbers), inplace=True)
/tmp/ipykernel_32572/2047506195.py:30: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  test_data[column].replace(element, sum(numbers)/len(numbers), inplace=True)
/tmp/ipykernel_32572/2047506195.py:24: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train_data[column].replace(element, sum(numbers)/len(numbers), inplace=True)
IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

,Kingdom,Phylum,Subphylum,Population size,Life span,Top speed,Weight,Height,Length,Attributes,Diet
0,0,0,-1,-3.991594e-16,15.0,45.0,38.5,67.5,51.5,2852,-1
1,0,0,0,-3.991594e-16,15.0,45.0,38.5,67.5,51.5,2804,-1
2,0,0,-1,-3.991594e-16,15.0,45.0,38.5,67.5,51.5,2832,-1
3,0,0,-1,-3.991594e-16,15.0,45.0,38.5,67.5,51.5,2852,-1
4,0,0,-1,-3.991594e-16,15.0,45.0,38.5,67.5,51.5,2852,-1
...,...,...,...,...,...,...,...,...,...,...,...
95,0,0,-1,-3.991594e-16,15.0,45.0,38.5,67.5,51.5,2842,-1
96,0,0,0,-3.991594e-16,30.0,8.0,453.0,67.5,16.5,1391,134
97,0,0,-1,-3.991594e-16,15.0,45.0,38.5,67.5,51.5,2852,-1
98,0,0,0,-3.991594e-16,15.0,45.0,6.5,67.5,51.5,2035,-1
99,0,0,0,-3.991594e-16,15.0,45.0,38.5,67.5,51.5,2804,-1

<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
آموزش مدل
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    حال که داده را پاکسازی کرده‌اید، وقت آن است که مدلی آموزش دهید که بتواند متغیر هدف این مسئله را پیش‌بینی کند.
</font>
</p>

In [41]:
# Design and train your model
# TODO
best_model, best_acc = None, None
X_train, X_val, y_train, y_val = train_test_split(train_data, _class, test_size=0.2, random_state=42)
# for n_estimators in range(5, 100, 5):
#     for max_depth in range(5, 20, 5):
#         model = RandomForestClassifier(n_estimators=n_estimators, max_depth=max_depth)
#         model.fit(X_train, y_train)
#         y_pred = model.predict(X_val)
#         acc = f1_score(y_val, y_pred, average='weighted')
#         if best_acc is None or acc > best_acc:
#             best_acc = acc
#             best_model = model
            
# AdaBoost model
from sklearn.ensemble import AdaBoostClassifier
for n_estimators in range(1000, 1001, 5):
    model = AdaBoostClassifier(n_estimators=n_estimators, learning_rate=.1)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_val)
    acc = f1_score(y_val, y_pred, average='weighted')
    if best_acc is None or acc > best_acc:
        best_acc = acc
        best_model = model

/home/keyhan/pytorch_env/pytorch_env/lib/python3.12/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
معیار ارزیابی
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    معیاری که برای ارزیابی عملکرد مدل انتخاب کرده‌ایم، <code>f1_score</code> نام دارد.
    <br>
    این معیار، سنجه ارزیابی کیفیت مدل شماست. به عبارت بهتر در سامانه داوری هم از همین معیار برای نمره‌دهی استفاده شده است.
    <br>
    پیشنهاد می‌شود با توجه به این معیار، عملکرد مدل خود را بر روی مجموعه‌ی آموزش یا اعتبارسنجی ارزیابی کنید.
</font>
</p>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font color="red"><b color='red'>توجه:</b></font>
<font face="vazir" size=3>
    برای دریافت نمره از این سوال لازم است تا دقت مدل شما از آستانه‌ی ۰.۴ بیشتر باشد.
    در صورتی که دقت مدل شما از ۰.۴ کمتر باشد نمره شما 
    <b>صفر</b>
    خواهد شد و در غیر این صورت با فرمول زیر محاسبه می‌شود:
</font>
</p>

In [42]:
from sklearn.metrics import f1_score
# Evaluate your model
# TODO
print(f'F1 Score: {best_acc}')

F1 Score: 0.7957147433365729

<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
 پیش‌بینی بر روی داده‌ی تست و خروجی
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    پیش‌بینی مدل خود بر روی داده‌های آزمون را در یک دیتافریم (<code>dataframe</code>) به فرمت زیر ذخیره کنید.
</font>
</p>


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    توجه داشته باشید که نام دیتافریم باید <code>submission</code> باشد؛ در غیر این‌صورت، سامانه‌ی داوری قادر به ارزیابی خروجی شما نخواهد بود.
    این دیتافریم صرفا شامل یک ستون به نام <code>Class</code> است و ۱۷۰۰ سطر دارد.
    <br>
    به ازای هر سطر موجود در مجموعه‌داده‌ی آزمون، باید یک کلاس پیش‌بینی‌شده داشته باشید و مقدار <code>Class</code> پیش‌بینی مدل شما برای آن سطر است.
    به‌عنوان مثال جدول زیر، ۵ سطر ابتدایی دیتافریم <code>submission</code> را نشان می‌دهد. البته این مقادیر به‌صورت فرضی هستند و در جواب شما، ممکن است متفاوت باشند.
</font>
</p>

<center>
<div align=center 
style="direction: ltr;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
||<code>Class</code>|
|:----:|:-----:|
|0|Gastropoda|
|1|Amphibia|
|2|Amphibia|
|3|Aves|
|4|Amphibia|

</font>
</div>
</center>

In [43]:
# Predict and save the predictions
# TODO
submission = pd.DataFrame(best_model.predict(test_data), columns=['Class'])
submission.to_csv('submission.csv', index=False)

<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
<b>سلول جواب‌ساز</b>
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    برای ساخته‌شدن فایل <code>result.zip</code> سلول زیر را اجرا کنید. توجه داشته باشید که پیش از اجرای سلول زیر تغییرات اعمال شده در نت‌بوک را ذخیره کرده باشید (<code>ctrl+s</code>) در غیر این صورت، در پایان مسابقه نمره شما به صفر تغییر خواهد کرد.
    <br>
    همچنین اگر از گوگل کولب برای اجرای این فایل نوت‌بوک استفاده می‌کنید، قبل از ارسال فایل <code>result.zip</code>، آخرین نسخه‌ی نوت‌بوک خود را دانلود کرده و داخل فایل ارسالی قرار دهید.
</font>

In [44]:
import zipfile
import os

if not os.path.exists(os.path.join(os.getcwd(), 'SharifML_Contest_ML.ipynb')):
    %notebook -e SharifML_Contest_ML.ipynb

def compress(file_names):
    print("File Paths:")
    print(file_names)
    compression = zipfile.ZIP_DEFLATED
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            zf.write('./' + file_name, file_name, compress_type=compression)

submission.to_csv('submission.csv', index=False)

file_names = ['SharifML_Contest_ML.ipynb', 'submission.csv']
compress(file_names)

File Paths:
['SharifML_Contest_ML.ipynb', 'submission.csv']